name: Remote SSH
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/KlatreBot/KlatreBot_Public/
            git pull
            source .venv/bin/activate
            pip install --upgrade -r requirements.txt
            
            # Update .env file with secrets
            tee .env > /dev/null <<EOF
            discordkey=${{ secrets.BOT_KEY}}
            openaikey=${{ secrets.OPENAI_API}}
            EOF
            
            # Update service file and restart
            sudo cp klatrebot.service /etc/systemd/system/klatrebot.service
            sudo systemctl daemon-reload
            sudo systemctl restart klatrebot
            sudo systemctl status klatrebot
