name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: updating klatrebot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd KlatreBot/KlatreBot_Public/
          git pull
          pkill python3
          nohup python3 KlatreBot.py ${{ secrets.BOT_KEY}}
