name: Remote SSH
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/KlatreBot/KlatreBot_Public/
            git pull
            source .venv/bin/activate
            uv pip install -r requirements.txt
            
            # Update environment file with secrets
            sudo tee /etc/klatrebot/klatrebot.env > /dev/null <<EOF
            DISCORDKEY=${{ secrets.BOT_KEY}}
            OPENAIKEY=${{ secrets.OPENAI_API}}
            EOF
            
            # Restart the service
            sudo systemctl restart klatrebot
            sudo systemctl status klatrebot
